name: classmate
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  cloud_firestore: ^4.8.1
  liquid_swipe: ^3.1.0
  get: ^4.6.5
  flutter_otp_text_field: ^1.1.1
  line_awesome_flutter: ^2.0.0
  firebase_core: ^2.14.0
  flutter_native_splash: ^2.3.1
  firebase_auth: ^4.6.3
  smooth_page_indicator: ^1.1.0
  flutter_svg: ^2.0.7
  google_fonts: ^5.0.0
  firebase_core_web: ^2.6.0
  firebase_auth_web: ^5.5.3
  cloud_firestore_web: ^3.6.2
  responsive_builder: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/splashscreen/
    - assets/images/onboarding/
    - assets/images/welcome/
    - assets/svgs/
    - assets/images/forgot_password/
    - assets/images/profile/
    - assets/images/signup/
    - assets/images/verifications/